### ISSUE TITLE
检查结果保存到 localStorage 或 cookie，下一次加载时，直接使用 fallback domain

### ISSUE THREAD

**Issue by PipecraftNet** [PipecraftNet/jsdelivr-auto-fallback#1]
结果保存一天。

**Comment by Andy17269** [comment]
在使用这个后，问题虽然可以解决，但好像网页打开的速度十分慢

**Comment by PipecraftNet** [comment]
> 在使用这个后，问题虽然可以解决，但好像网页打开的速度十分慢

原来的 JS 加载因为一直处在 pending 状态，导致新的 JS （gcore.jsdelivr.net） 加载被阻塞。
这个问题如何解决还在不断尝试中。

**Comment by PipecraftNet** [comment]
> 在使用这个后，问题虽然可以解决，但好像网页打开的速度十分慢

@Andy17269 刚刚提交了新版本，性能提升了很多。如果在使用，请试一试新版本。

注意：所有 `script` 标签加上 `defer` 属性。如果原来有 `async` 属性，可以跳过。这个可以避免 `pending` 状态带来的等待时间，大大提升性能。

**Comment by Andy17269** [comment]
> > 在使用这个后，问题虽然可以解决，但好像网页打开的速度十分慢
> 
> @Andy17269 刚刚提交了新版本，性能提升了很多。如果在使用，请试一试新版本。
> 
> 注意：所有 标签加上 属性。如果原来有 属性，可以跳过。这个可以避免 状态带来的等待时间，大大提升性能。`script``defer``async``pending`

好的，谢谢

**Comment by PipecraftNet** [comment]
Done. [v0.2.0](https://github.com/PipecraftNet/jsdelivr-auto-fallback/releases/tag/0.2.0) [diff](https://github.com/PipecraftNet/jsdelivr-auto-fallback/commit/843e9d2e6f9eb6ace8eef5cdb942589c202a8f17)
