### ISSUE TITLE
记录用到这个项目的地方，方便有必要的更新时，提醒对方修改。

### ISSUE THREAD

**Issue by PipecraftNet** [PipecraftNet/jsdelivr-auto-fallback#3]
记录用到这个项目的地方，方便有必要的更新时，提醒对方修改。

- https://discuss-cn.bestxtools.com/
- https://github.com/v2hot/v2hot.github.io
- https://github.com/ngc7331/server-update-manager

如果有其他项目用到了，请以评论方式补充。

**Comment by Yxliam** [comment]
https://www.toolbon.com/

**Comment by dunhuixiao** [comment]
https://github.com/dunhuixiao/LiyuTargetMon/

**Comment by GuihongWang** [comment]
blog.marisa.ml 
联系方式（一个比一个级别高）：
3.marisa@marisa.ml
2.minecraftis1st@outlook.com
1.qq：2984188181

**Comment by terwer** [comment]
https://terwergreen.com
联系方式：youweics@163.com

**Comment by terwer** [comment]
https://terwergreen.com/

**Comment by paradoxsugar** [comment]
https://www.ljcgo.com
contact me by paradoxsugar@outlook.com
